### ISSUE TITLE
Wiki 文档 Review 的一些反馈和总结

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#1]
1. Markdown的格式问题。大家在wiki上提交的文档，格式上有不少问题。很常见的一种错误是写标题时`#`后不加空格，比如写成`##head`，正确的应是`## head`。还有表格少写`|`的。这些都是可以避免的。建议大家提交之前在`Preview`里粗略看一下GitHub生成出的文档是不是有typo。我把大家文档中的typos都直接改掉了。
2. 类成员写的是`properties`，我建议写成`fields`，成员函数写的是`functions`, 我建议写成‘methods·。这样更符合`面向对象建模方法(OO)`的习惯。这个我没有改，看大家的习惯，统一就好。

Wiki文档没法comment，我就直接提了这个issue。

**Comment by xxr5566833** [comment]
恩恩  最后的格式有问题
这里我用properties主要是cocos creator中是用properties

**Comment by si1entic** [comment]
我试了一下，creator里把properties改成fields会报错。
`Unknown type of Company.fields, property should be defined in 'properties' or 'ctor'`
应该是不支持，functions同理

**Comment by YoungForest** [comment]
那还是按照`properties`和`functions`就可以，依照cocos的习惯来。可能是我Java写多了（笑。
