### ISSUE TITLE
UI/calendar类中getYearMonthWeek函数的实现增强

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#106]
https://github.com/xxr5566833/Game/blob/3baa638c676412607335695a55905c92e0175437/assets/Script/UI/calendar.js#L45
此函数的输入为：一个天数；
输出为：此天数代表的年数，月数和周数。
实现方式为：一天一天的向上数，遇到一周就在周数上加一；遇到一月就在月数上加一，同时周数清零；遇到一年就在年数上加一，同时月数和周数清零。
这种实现方式固然可行，但存在效率问题，时间复杂度为O(n)。获取年月周数完全可以O(1)实现。
而且这个函数每次update都要调用，有优化的必要。

**Comment by hanayashiki** [comment]
这个我一开始也想过o（1），但是闰年处理太复杂了...不好意思，而且应该影响不大

**Comment by hanayashiki** [comment]
考虑到游戏时间可能在1000-2000的范围内，开销都不是很大..

**Comment by YoungForest** [comment]
这样，看来实际情况确实不需要优化。这个issue我就直接close了。
