### ISSUE TITLE
除0错误

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#107]
https://github.com/xxr5566833/Game/blob/3baa638c676412607335695a55905c92e0175437/assets/Script/UI/development.js#L63
在这里project的requireUI_默认为0，会出现除零错误，此时width为NaN。我没看懂这里处理UI的逻辑，具体得到ui bar的宽度有什么用处，不太清楚这里是bug还是feature。

**Comment by FelixCaae** [comment]
这个解决了吗？解决了可以关一下？
