### ISSUE TITLE
完成公式的基本策划

### ISSUE THREAD

**Issue by JerryYouxin** [xxr5566833/Game#116]
软件属性点数累计
Bug产生
科研点数产生
软件收益计算
总预计时间10h

**Comment by 514DNA** [comment]
软件属性点数累计：
    F = (1 / (n ^ (50 / (manager + 50)))) *( Coding / 10) * (rand(0.9 , 1.1))
    P = (1 / (n ^ (50 / (manager + 50)))) *( Science / 10) * (rand(0.9 , 1.1))
    E = (1 / (n ^ (50 / (manager + 50)))) *( Art / 10) * (rand(0.9 , 1.1))
    I = (1 / (n ^ (50 / (manager + 50)))) *( Creater / 10) * (rand(0.9 , 1.1))

**Comment by 514DNA** [comment]
软件收益计算：
m = sqrt(7*E + 3*P) *F *(t + sqrt(I))/t
m0 = 1000 * sqrt(T)
Ve = F  / 33
m' = Ve * m / V          // V为定价
n(用户数量) = m'/ (m' + m0)

**Comment by JerryYouxin** [comment]
Bug产生新建了issue #126

**Comment by JerryYouxin** [comment]
科研点数产生：
在开发过程中发生暴击科研点数增加1~3之中的随机数
如果有专门的科研人员：S = (Science/10)*rand(0.9,1.1)

**Comment by 514DNA** [comment]
BUG产生:
如果F == 0，那么BUG数量就为 0
如果F != 0 ，那么总BUG数量基准值为B0 = F*t/25           //t为生产周数
那么总BUG数量范围为 [B0/(1 + (0.1*I / F)) , B0 * (1 + (0.1*I / F))]           //随机取里面的值
高级BUG数设为HB, 中级BUG数为MB，低级BUG数为LB
那么，HB 范围为 [0.05B , 0.15B]
          MB 范围为 [0.2B , 0.4B]
          LB = B - HB -MB
三个等级的BUG数量，已发现的BUG和未发现的BUG均为6:4

**Comment by JerryYouxin** [comment]
暴击率：   Creator/(Creator+200)
暴击倍率： 1+(5*sqrt(Science))/100

**Comment by JerryYouxin** [comment]
实际花费1h
