### ISSUE TITLE
软件开发难度相关详细策划设计

### ISSUE THREAD

**Issue by JerryYouxin** [xxr5566833/Game#127]
预计3h

**Comment by JerryYouxin** [comment]
难度计算：
+ 外包软件的难度为设定难度
+ 自主开发软件的难度为技术难度+平台难度+类型难度+功能难度
难度会影响属性累计速度

**Comment by 514DNA** [comment]
减少的任务点数增量百分比 = (任务难度 * 0.06) / (任务难度 * 0.06 + 1)

**Comment by JerryYouxin** [comment]
实际2h
