### ISSUE TITLE
所有公式汇总

### ISSUE THREAD

**Issue by JerryYouxin** [xxr5566833/Game#130]
这里含有所有公式相关的issues

**Comment by JerryYouxin** [comment]
issue #126 
issue #128 
issue #116
isssue #127  
issue #132

**Comment by 514DNA** [comment]
测试阶段，每产生3点功能点（计算难度的影响，但是该功能点不加入项目的属性点），有75%的概率减少一个已发现的BUG，同时有50%的概率发现一个未发现的BUG

**Comment by xxr5566833** [comment]
减少和发现的bug等级机制？    bug分为三个等级每一次减少哪个等级。。

**Comment by JerryYouxin** [comment]
issue #121 

启动开发所花费预算计算方法:

软件预计功能点设为F_e，则，启动开发的预算的计算公式为：预算=F_e/10，单位为万。

**Comment by JerryYouxin** [comment]
@xxr5566833 减少bug的等级机制：减少一个bug时，随机选择一个bug等级进行减少，概率分布为：

+ 高级：50%
+ 中级：30%
+ 低级：20%

其中如果随机到某一级却没有bug可供修复，向下降级，以此类推直到有bug可以修复；如果已经没有已发现bug可以修复，则忽略这个bug修复信息。

**Comment by JerryYouxin** [comment]
实际8h
