### ISSUE TITLE
公司活动机制详细设计方案

### ISSUE THREAD

**Issue by JerryYouxin** [xxr5566833/Game#131]
预计2h

**Comment by JerryYouxin** [comment]
需要定义清楚活动类型，每种类型活动产生的效果，每种活动类型都先设计大约两个活动。

**Comment by 514DNA** [comment]
具体活动我以EXCEL表格形式发在群里了

下面是活动对话池：
    1.这个活动对我收益很大
    2.很期待下次的活动
    3.真好玩……不想下班了
    4.公司对我真好
    5..........................................好（寡言限定，且寡言只说这一句）
    6.祝愿公司会借着这次活动越办越好
    7.好兴奋……好累
    8.浩瀚的宇宙啊……（太空体验活动限定）
    9.地球好渺小，我们更渺小……（太空体验活动限定）
    10.太空好美……（太空体验活动限定）
    11.好险……差点挂掉了（野外探险活动限定）
    12.吃坏肚子了……（野外探险活动限定）
    13.大自然，真美……（野外探险活动限定）
    14.原来世界上还有这样的奇观……（环球旅行活动限定）
    15.（意大利面| 法国牛排| 日式拉面| 印度咖喱| 土耳其烤肉） 真好吃…… （环球旅行活动限定）
    16. 原来历史上……还发生过这样的事情……长见识了……（环球旅行活动限定）
    17. 这里居然用到了位运算，还好我看懂了提示……（大型密室逃脱限定）
    18. 这个地方的谜题，居然要用到编程知识，还好我们都会……（大型密室逃脱限定）
    19. 啊啦啊啦，就没有难一点的谜题么……（大型密室逃脱限定）
    20. XXX（员工名），为什么你的Q总是往反方向放……（电子竞技比赛限定）
    21. XXX（员工名），为什么你这把只打出了4396点伤害……（电子竞技比赛限定）
    22. XXX（员工名），求求你别秀了，秀的我头皮发麻……（电子竞技比赛限定）

**Comment by JerryYouxin** [comment]
已更新到wiki
