### ISSUE TITLE
Wiki 文档

### ISSUE THREAD

**Issue by easylliu** [xxr5566833/Game#2]
### 人员的雇佣和解雇
雇佣调用的函数和解雇调用的函数是不是写反了
用户选定某个人员并决定## 雇佣后，会触发personGenerator.## removePerson()的方法
用户选定某个人并决定## 解雇后，会触发personGenerator.## addPerson()方法

api reference：
1.Project属性建议可将功能属性扩展（功能性，可靠性，易使用性，效率，可维修性，可移植性取其中几个）
2.Project属性3和5都是状态位重复了，可取其一

**Comment by xxr5566833** [comment]
上次写的没有提交上去？我记得我回答了，这里补一下：
1.决定雇佣后，会把这个人从personGenerator的persons_数组里删去，所以调用removePerson方法，然后解雇时，会把这个人重新加到personGenerator 的persons_数组里，所以这里应该没有写反，只不过名字可能不够直观？
2.取了 ui和func了
3.已改
