### ISSUE TITLE
注释，调试，文档规范的统一

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#27]
# 注释风格
共遇到三种风格：
```
\** comment *\
\* comment *\
\\ comment
```
这些注释并不是说，不同类型的注释使用不同的格式。而是使用的地方也都有，对properties的注释，对function的注释，普通注释。建议开发组统一一下注释的规范。比如解释function可以用`\** comment *\`，解释properties可以用`\* comment *\`，之类的。

# 关于调试
目前大家广泛使用输出log调试，但是有些地方用`cc.log()`，有些地方用`console.log()`，我不太清除这两者的区别。是否有必要统一使用一种`log`呢？大家可以商榷一下。

# 代码与文档不符的问题
这个问题可能是开发中比较常见的也很难避免的。因为实际开发会遇到各种之前很难遇见的事情，边写代码边改文档也比较麻烦。但是还是希望大家commit之后对照更新文档。这样有据可依，其他人在测试和review时也可以更好地理解代码。

比如：
https://github.com/xxr5566833/Game/blob/f2c14c2ffb185846c6ba76cb9bf98ae657c66c6a/assets/Script/firstscene/Person.js#L12
这里增加了新的属性`ability`，是指总的ability（由其他6个ability计算得出）还是与其他6个ability无关。这种注释里没有解释，文档里也没有的。review人员很难理解。下面还用到这个变量了，我就很难判断意图，容易隐藏bug。

**Comment by 514DNA** [comment]
之前那个ability是调试用的变量，没有实际意义，现在已删

**Comment by xxr5566833** [comment]
1. 统一使用cc.log()
2. 统一注释风格：鉴于VScode 会自动帮你生成\/  \*\* \* \/风格的注释，规定无论是属性还是方法，单行就用\/\/多行就用\/  \*\* \* \/
