### ISSUE TITLE
ProjectGenerator类createProjects方法的逻辑问题

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#3]
https://github.com/xxr5566833/Game/blob/a54da707612d5bcd42c9972d0a6ee02c09b54611/assets/Script/firstscene/ProjectGenerator.js#L36
这里是否需要增加`return;`，以及之后41行判断有`project`是已被接受且成功或者失败，的`if`语句里是否也应该增加`return;`。因为这些情况下即使重新生成任务后，44行的`console.log('三个任务都没有变');`都会被执行，与本意相悖。

**Comment by xxr5566833** [comment]
对 这里确实有问题！

**Comment by xxr5566833** [comment]
已改，就关闭了
