### ISSUE TITLE
代码实现与文档不一致问题

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#4]
https://github.com/xxr5566833/Game/blob/a54da707612d5bcd42c9972d0a6ee02c09b54611/assets/Script/firstscene/ProjectGenerator.js#L56
在[wiki->点单的代码约定](https://github.com/xxr5566833/Game/wiki/%E7%AE%80%E5%8D%95%E7%9A%84%E7%BC%96%E7%A0%81%E7%BA%A6%E5%AE%9A)中，我们约定了要保证文档与代码的一致性。而在这里和
https://github.com/xxr5566833/Game/blob/a54da707612d5bcd42c9972d0a6ee02c09b54611/assets/Script/firstscene/ProjectGenerator.js#L83
https://github.com/xxr5566833/Game/blob/a54da707612d5bcd42c9972d0a6ee02c09b54611/assets/Script/firstscene/ProjectGenerator.js#L46
的两个函数都是在文档中没有具体说明的。另外，我还想确认一点，咱们文档中API描述，是只需要描述共有方法，不需要描述私有方法吗？还是都需要。（js不分共有私有，但是我们可以根据是否类外被调用来在行为上进行区分）。

**Comment by xxr5566833** [comment]
1.确实因为目前游戏具体的内容还没有定下来，所以这里一些方法的定义都是我因为调试方便而定义了一些临时方法，在最后是可以删除的，还有一些方法是需要在文档里更新的。
但是目前更新我想等游戏具体内容定下来后，更新api文档，这里我把所有与文档不一致的地方都做了标注，所以可以保证最后的一致性。但是这里确实没有严格遵守文档的修改规定，这个情况以后会尽量避免的。
2.关于公有方法和私有方法，这里我还没有想好，我觉得肯定是需要的。
技术上：cocos creator的私有属性可以通过在properties里仅仅设置get方法来实现，但是私有方法目前还没有想好怎么实现
行为上：我需要经过思考然后确定下来，到时候大家一起审核一下

**Comment by xxr5566833** [comment]
1.已经把调试用的不用的函数删去，更新了文档
2.公有私现在没太多时间看相关内容，不过我会在初步功能实现后，尽快确定下来的，
