### ISSUE TITLE
Date类update函数中帧计数器清零bug

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#48]
https://github.com/xxr5566833/Game/blob/f42ed662b6230b6717a1e15db395a50a9f590b30/assets/Script/firstscene/Date.js#L29
在这里，代码的意图显然是当`count_ >= speedPerday`时，天数加一，同时`count_`清零。而这里，开发人员少写了`{}`，使得实际执行变为，每帧都清零，而天数不会增长，是一个严重的bug。开发人员可能是`Python`写多了，不习惯`JavaScript`的coding。[`api reference`文档中这部分函数说明](https://github.com/xxr5566833/Game/wiki/api-reference#3-update)也有同样的错误。

**Comment by crvz6182** [comment]
已在本地进行修改，下一次提交时会更正
