### ISSUE TITLE
Project类中对每个私有属性实现了`set`和`get`方法，是否有必要？

### ISSUE THREAD

**Issue by YoungForest** [xxr5566833/Game#5]
https://github.com/xxr5566833/Game/blob/a54da707612d5bcd42c9972d0a6ee02c09b54611/assets/Script/firstscene/Project.js#L103
比如这里的`setCurrent()`方法，我认为不应该出现。因为已经有`augment()`方法对私有属性进行增加操作，这个方法已经符合我们需要了。而`setCurrent()`方法没有存在的理由，因为一个项目的进度不会出现任意变化的现象。

**Comment by xxr5566833** [comment]
这一点我同意，current属性就应该仅仅通过augment来实现
考虑到封装性这个方法肯定不能随随便便就公开出来，这里我会在保证游戏接下来的内容确实不需要这个方法后删除它。

**Comment by xxr5566833** [comment]
setCurrent()已删
