### ISSUE TITLE
Finish getEmployeeList() and fire() in UI/fire.js

### ISSUE THREAD

**Issue by hanayashiki** [xxr5566833/Game#68]
在master上将最新commit pull到本地，注意game.fire如果冲突应该全部用新的game.fire中的改动
注释有误，下个commit修正；
fire需要完成：开除index指定的员工
getEmployeeList返回指定格式的当前已雇佣员工

**Comment by si1entic** [comment]
已提交，并调试出一个UI的bug：
fire.js里多个函数用到this.candidates，但properties里并没有该属性，所以运行时显示undefined。
已添加该属性。
实测雇佣+解雇功能已完成。

一个建议：
每个子窗口能否增加返回/取消按钮。比如玩家查看可雇佣列表后选择放弃，目前只再点左侧按钮，不太友好。

**Comment by hanayashiki** [comment]
我计划是点击外部即可返回，还没实现。。
